apiVersion: v1
kind: Service
metadata:
  name: detector
spec:
  type: NodePort
  selector:
    app: detector
  clusterIP: 10.96.18.123
  ports:
  - port: 8080
    targetPort: 3000
    nodePort: 30033
